@extends('layouts.app')
@section('title', 'About Sean')

@section('content')
	<div class="container mx-auto py-10">
		<h1 class="mb-4">About Sean</h1>
		<p class="mb-4">Sean Anthony Wilson, passed away peacefully in his sleep on the morning of November 25, 2015 at his home in Palmdale, California after a short fight with liver disease. Sean was born in the early morning of August 18, 1984 in Pasadena, California to his parents Stanley and Sharie Wilson. After spending the first 10 years of his life in Highland Park, California, Sean moved to Palmdale with his family in 1994 where he attended Hillview Middle School and graduated from Highland High School in 2002. After high school, Sean spent some time deciding what he wanted to do before making his next move.</p>

		<p class="mb-4">One thing about Sean, once he decided what he wanted to do, there was no stopping him. He enrolled at Antelope Valley College where he earned his Associate's Degree in Criminal Justice before continuing to California State University, Los Angeles, where he graduated in 2011 with a Bachelors of Science in Business Administration with a minor in Human Resources. Sean was a beloved son and brother who was wise beyond his years and was an extremely caring person who was always concerned about the well being of others in his life. He'd take hours out of his time to sit and talk with a friend or family member who was struggling through an issue. He was always full of life and energy and could brighten any mood with a well timed joke or fart.</p>

		<p class="mb-4">In his spare time, Sean enjoyed working out at the gym, playing basketball and watching wrestling, boxing, UFC, football and basketball and spending time with his dog Sophie. He loved trying new buffets - especially Chinese buffets. Sean was a fan of the New York Yankees, Chicago Bulls and a fan of whoever was playing the Lakers - just to antagonize his father. His favorite movie was Coming to America, and he could quote pretty much the entire movie. He was a huge fan of both Michael Jackson and Michael Jordan. He also enjoyed cooking and travelling. Sean was very interested in his familial background and knowing where his ancestors came from. His travels took him first to San Francisco, New York, and Washington DC before he traveled all the way to Hong Kong and mainland China all on his own so he understand his roots. Sean is survived by his parents Stanley and Sharie; his older brother Stanley and his wife Jeanine and his nephew Isaiah; his younger brother Scott; his Uncle Marti and Aunt Linda and his cousins Christopher, Stephen and David. He is also survived by his beloved Shih Tzu/Yorkie mix, Sophie.</p>
	</div>
@endsection